include $(root)/swl/Makefile.conf

LIBS += swl

ifeq ($(SWL_BACKEND_XLIB),1)
LIBS += X11
endif

ifeq ($(SWL_CONTEXT_EGL),1)
include $(root)/egl/Makefile.public
endif

ifeq ($(SWL_CONTEXT_WGL),1)
LIBS += gdi32
endif

ifeq ($(SWL_OPENGL_ES),1)
include $(root)/gles/Makefile.public
endif

ifeq ($(SWL_OPENGL),1)
include $(root)/glew/Makefile.public
ifeq ($(SWL_BACKEND_WINAPI),1)
LIBS += opengl32
else
LIBS += GL
endif
endif
