#pragma once

#define SWLR_ERROR_CONTEXT_EGL_DISPLAY_CREATION SWLR_CONTEXT(0)
#define SWLR_ERROR_CONTEXT_EGL_SURFACE_CREATION SWLR_CONTEXT(1)
#define SWLR_ERROR_CONTEXT_EGL_CONTEXT_CREATION SWLR_CONTEXT(2)
#define SWLR_ERROR_CONTEXT_EGL_CREATION SWLR_CONTEXT(3)
#define SWLR_ERROR_CONTEXT_EGL_CONFIG SWLR_CONTEXT(4)
#define SWLR_ERROR_CONTEXT_EGL_ERROR SWLR_CONTEXT(5)
