#pragma once
#include "windows.h"	

/*
 * Key type definition
 */
typedef DWORD swl_key_t;

#define SWLK_UP VK_UP
#define SWLK_DOWN VK_DOWN
#define SWLK_LEFT VK_LEFT
#define SWLK_RIGHT VK_RIGHT
#define SWLK_GO VK_RETURN

#define SWLR_ERROR_PLATFORM_WINAPI_REGISTER_CLASS SWLR_PLATFORM(0)
#define SWLR_ERROR_PLATFORM_WINAPI_HANDLE SWLR_PLATFORM(1)
#define SWLR_ERROR_PLATFORM_WINAPI_DEVICE SWLR_PLATFORM(2)
