#pragma once
#ifndef NOMINMAX
	#define NOMINMAX
#endif
#define WIN32_LEAN_AND_MEAN
#define WINVER 0x0502
#include "windows.h"

typedef HWND swl_window_t;
typedef HDC swl_display_t;

#define SWLR_ERROR_BACKEND_WINAPI_REGISTER_CLASS SWLR_BACKEND(0)
#define SWLR_ERROR_BACKEND_WINAPI_HANDLE SWLR_BACKEND(1)
#define SWLR_ERROR_BACKEND_WINAPI_DEVICE SWLR_BACKEND(2)
#define SWLR_ERROR_BACKEND_WINAPI_RAW_INPUT SWLR_BACKEND(3)
